import os, time
os.system('xdotool key super+s')
os.system('clear')
print('\n\n\n\n\n\n\n\n')
print('		⎧							⎫')
print('		⎪							⎪')
print('		⎪		 	1 poweroff			⎪')
print('		⎪							⎪')
print('		⎪		 					⎪')
print('		⎪							⎪')
print('		⎪		 	2 reboot			⎪')
print('		⎪							⎪')
print('		⎪							⎪')
print('		⎪							⎪')
print('		⎪		 	3 suspend			⎪')
print('		⎩							⎭')
action = input()
if action == '1' : os.system("systemctl poweroff")
elif action == '2' : os.system("systemctl reboot")
elif action == '3' : os.system("systemctl suspend && slock")
else : os.system("clear && echo '\n\n\n\n\n\n\n\n\n\n\n' && figlet '                   BAD   INPUT'")
time.sleep(1)
os.system('xdotool key super+w')
